### ISSUE TITLE
Why does a 403 result in a stack crawl to log?

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1025]
On prod:
```
[29/Nov/2022 13:10:08,252] WARNING[log.py:241 (log_response)] Forbidden (Permission denied): /d/
Traceback (most recent call last):
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 134, in dispatch
    return self.handle_no_permission()
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
[29/Nov/2022 13:15:33,425] WARNING[log.py:241 (log_response)] Forbidden (Permission denied): /d/
Traceback (most recent call last):
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 134, in dispatch
    return self.handle_no_permission()
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied

```

**Comment by Shriukan33** [comment]
Not having the permission to access something (here the dashboard) is raising permissionDenied error, which is logged as warning.

I don't know why this is logged as warning but I think it's by design? Someone is trying to access something they're not allowed to accessed after all.

**Comment by JeffAbrahamson** [comment]
I'm ok with the log message.
What I'm wondering is why the log message is a stack trace.

**Comment by Shriukan33** [comment]
I don't really know, my guess on this is because warning are more verbose to allow debug. It doesn't seem to be a bug to me ?

I've reproduced this behavior on a different url no problem. 403 is from an error raising. 
![image](https://user-images.githubusercontent.com/70256364/204755321-8d3c420a-8fa4-4139-9714-c513ddd0d73f.png)

**Comment by JeffAbrahamson** [comment]
Your explanation seems a bit too easy for me: too much "I guess" and "the library did it".  When I see a stack trace in my logs, I'm suspicious.

Digging a (very tiny) bit, I found this [SO article](https://stackoverflow.com/questions/68736735/django-prints-error-when-permissiondenied-exception-raises), which led me to [this doc page](https://docs.djangoproject.com/en/3.2/topics/auth/default/#django.contrib.auth.decorators.permission_required).

This makes me think that we should add a `LoginRequired` decorator (when using the `PermissionRequired` decorator) or similarly with mixins (which is the case with `DashboardIndex`).

This isn't the highest priority task we face, but I really don't believe that stack traces in the log represent everything functioning as intended.  And the above resources suggest it is not, even if it's likely to require some fiddling to get right.
