### ISSUE TITLE
press mention typo leads to 500

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1033]
```
[30/Nov/2022 18:53:10,083] INFO[views.py:237 (update_opengraph_data)] No opengraph data at https://actu.fr/pays-de-la-loire/nantes_44109/les-voitures-de-retour-sur-le-pont-saint-mihiel-a-nantes-le-symbole-d-une-metropole-qui-hesite_39297453.html.
[30/Nov/2022 18:55:03,503] ERROR[log.py:241 (log_response)] Internal Server Error: /presse/admin/list/
Traceback (most recent call last):
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/var/www/tn-prod2/transport_nantes/press/views.py", line 72, in get_context_data
    update_opengraph_data(
TypeError: update_opengraph_data() got an unexpected keyword argument 'presmention_id'
```

**Comment by JeffAbrahamson** [comment]
Cf. also https://rollbar.com/mobilitains/tn-prod/items/11/
