### ISSUE TITLE
dashboard throws, shouldn't

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1176]
Repro: login as jeff@mobilitain.fr, click `/d/` -> view mails.

```
[16/Jun/2023 14:11:52,635] WARNING[log.py:241 (log_response)] Forbidden (Permission denied): /tb/admin/e/list/
Traceback (most recent call last):
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 108, in dispatch
    return self.handle_no_permission()
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
```

**Comment by JeffAbrahamson** [comment]
I don't have permission.  It should say that, not brusquely 403 without explanation.

The non-dev user seeing a 403 will say "the site is broken" instead of "the site says I need permission X.y.z to continue, could you help?".
