### ISSUE TITLE
stripe errors

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#298]
Before 10 Nov 2021 I see occasional errors in the logs about stripe malfunctions.  Did these stop because they were fixed (let's link the commit here) or did they stop because they just haven't been tickled since?

They aren't all the same, but here's an example:

```
[09/Nov/2021 16:30:26,785] Internal Server Error: /donation/create-checkout-session/
Traceback (most recent call last):
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/var/www/tn-prod2/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view stripe_app.views.create_checkout_session didn't return an HttpResponse object. It returned None instead.

```

**Comment by Shriukan33** [comment]
Checked on the code of create_checkout_session (as it claimed to be the one at fault here : ValueError: The view stripe_app.views.create_checkout_session didn't return an HttpResponse object.) 

There are no "return None", it's supposed to be JSONResponse. 
This function in fact, gets information from the form and returns a dict containing a sessionID, that is then used to redirect the user to its checkout session. 

I looked up the error message you gave to see what errors are beside it, it's a bunch of "Not found : /<some url>"

```
[09/Nov/2021 18:07:49,904] Forbidden (Referer checking failed - Referer is malformed.): /
[09/Nov/2021 18:13:52,103] Not Found: /static/velopolitain/panneau-pieton-velo.jpg
[09/Nov/2021 18:13:52,260] Not Found: /static/asso_tn/20210228-210131-9011_velorution-psm-667.jpg
[09/Nov/2021 18:13:52,393] Not Found: /static/velopolitain/v4.png
[09/Nov/2021 18:13:52,534] Not Found: /static/velopolitain/tactical/provisoire-3.jpg
[09/Nov/2021 18:13:52,692] Not Found: /static/velopolitain/v3.png
[09/Nov/2021 19:51:58,924] Not Found: /observatoire/nantes/marker-icon.png
[09/Nov/2021 19:52:01,360] Not Found: /observatoire/nantes/marker-icon-2x.png
[09/Nov/2021 19:52:05,334] Not Found: /observatoire/nantes/marker-shadow.png
[09/Nov/2021 19:52:09,671] Not Found: /releases/
[09/Nov/2021 19:52:13,401] Not Found: /kit-upload.css
[09/Nov/2021 19:52:16,545] Not Found: /releases/v
[09/Nov/2021 19:52:19,838] Not Found: /webfonts

```

Those are the next. 

I managed to reproduce the Error by manually entering the URL inside the browser, while a `curl -I https://www.mobilitains.fr/donation/create-checkout-session/ ` does a 301.

So my take is, I maybe did enter this URL to test what would happen, or someone else did (but not very likely). 
If you're aware of other ways to reproduce ... ?
