### ISSUE TITLE
Can't login using magic link : Token too long for django 

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#590]
Here is the log from beta : 

```
[30/Mar/2022 08:55:18,570] form_valid
[30/Mar/2022 08:55:18,570] benjamin@mobilitain.fr loggin request.
[30/Mar/2022 08:55:18,576] Sending email to benjamin@mobilitain.fr
[30/Mar/2022 08:55:37,274] Internal Server Error: /auth/activate/MmxyZ1p0SDFwdWZYOEVRcmdpakF4VTl5TXE0fDkyNDVkYjdiZTRmODMzNTVlZGU3NjQ0NGY5ODg4ODlhNzM2ODJjYWNlM2E3MTZiM2RkNjYyNzkxYWYyZDA4NWR8YmVuamFtaW5AbW9iaWxpdGFpbi5mcnxyOWp3ZGl8MHwwZDIxNjliMDc5ZDk2ODA5MjU1YQ
Traceback (most recent call last):
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(200)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/tn-beta2/transport_nantes/utm/middleware/utm.py", line 64, in __call__
    utm.save()
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/www/tn-beta2/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(200)
```

Step to replicate : 
Go to /auth/in and fill the form with your email address ending in @mobilitain.fr (otherwise you can't receive the email) 
Check your mailbox and copy / paste the received link in your browser
The browser shows 500. 

It seems to stem from the UTM model : 
https://github.com/transport-nantes/tn_web/blob/196fd653cc703d1e30a05c583293bc05ae5acb7c/transport_nantes/utm/models.py#L25

**Comment by JeffAbrahamson** [comment]
Yup, the clue was that it was talking to postgres when it got the error.  Just increase that charfield max to 300 and be done with it.

Postgres doesn't pay attention to the max_length, so it's pretty much free.

**Comment by Shriukan33** [comment]
On additional note : It also prevents unsubscription to happen for the very same reason (too long url)

The fix is indeed easy enough
